### ISSUE TITLE
Add general indicators section

### ISSUE THREAD

**Issue by atrueblood** [DCgov/economic-intelligence#5]
Population, GDP, etc.

**Comment by mseew** [comment]
Check out the "Quick Stats" section on the intro page. Does it make more sense to leave just the quick stats on the intro page and remove all other charts? I ask because there are deeper dives into some of the quick stats (i.e. population detail) which would be duplicative to include also if we're operating on the principle of including all charts on the intro page.

**Comment by atrueblood** [comment]
That makes sense to me

Best,
Andrew

Andrew Trueblood
Chief of Staff
Office of the Deputy Mayor for Planning & Economic Development
Government of the District of Columbia
202.724.7906tel:202.724.7906 | Direct
202.727.6365tel:202.727.6365 | Office
andrew.trueblood@dc.govmailto:andrew.trueblood@dc.gov

http://mayor.dc.govhttp://mayor.dc.gov/

On Dec 28, 2015, at 3:47 PM, Marie Whittaker <notifications@github.com<mailto:notifications@github.com>> wrote:

Check out the "Quick Stats" section on the intro page. Does it make more sense to leave just the quick stats on the intro page and remove all other charts? I ask because there are deeper dives into some of the quick stats (i.e. population detail) which would be duplicative to include also if we're operating on the principle of including all charts on the intro page.

—
Reply to this email directly or view it on GitHubhttps://github.com/DCgov/economic-intelligence/issues/5#issuecomment-167651079.

Check out DMPED’s new Real Estate Project Pipelinehttp://dmped.dc.gov/page/real-estate-projects for real time updates on the status of real estate projects located across the District of Columbia.
